source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'iOSArchitectureMVVM' do
pod 'Alamofire', '~> 4.0.1'
pod 'SwiftyJSON', '~> 3.1.1'
pod 'Kingfisher', '~> 3.2.0'

end
